# This file is a template, and might need editing before it works on your project.
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Go.gitlab-ci.yml


stages:
#  - build
#  - test
  - build-docker-image

#compile:
#  stage: build
#  image: golang:latest
#  tags:
#    - docker
#  script:
#    - mkdir -p binaries
#    - go build -o binaries ./...
#  artifacts:
#    paths:
#      - binaries

#test:
#  stage: test
#  image: golang:latest
#  tags:
#    - docker
#  script:
#    - go test ./... -v

build-docker-image:
  stage: build-docker-image
  image: alpine:latest
  tags: 
    - docker

  services:
  - docker:dind
  before_script:
  - apk update
  - apk add docker
  - dockerd --experimental --host=unix:///var/run/docker.sock
  script:
    - docker context ls
    - docker info
    - docker buildx create --use
    - docker buildx build --platform linux/amd64 -t user-service:x86 .
