# This file is a template, and might need editing before it works on your project.
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Go.gitlab-ci.yml


stages:
#  - build
#  - test
  - build-docker-image
  - deploy

#compile:
#  stage: build
#  image: golang:latest
#  tags:
#    - docker
#  script:
#    - mkdir -p binaries
#    - go build -o binaries ./...
#  artifacts:
#    paths:
#      - binaries

#test:
#  stage: test
#  image: golang:latest
#  tags:
#    - docker
#  script:
#    - go test ./... -v

#build-docker-image:
#  stage: build-docker-image
#  image: docker:latest
#  tags: 
#    - docker-build
#  services:
#    - docker:dind
#  variables:  # not strictly needed, depending on runner configuration
#    DOCKER_HOST: "tcp://docker:2375"
#    DOCKER_TLS_CERTDIR: ""
#
#    IMAGE_NAME: "user-service:x86"
#    AZURE_REGISTRY_USERNAME: $CI_REGISTRY_USER
#    AZURE_REGISTRY_PASSWORD: $CI_REGISTRY_PASSWORD
#    AZURE_REGISTRY: dentanoidregistry.azurecr.io
#
#  script:
#    - docker context ls
#    - docker info
#    - docker buildx create --use
#    - docker buildx build --platform linux/amd64 -t $IMAGE_NAME . --load
#    - docker tag $IMAGE_NAME $AZURE_REGISTRY/services/user
#    - docker login $AZURE_REGISTRY -u $AZURE_REGISTRY_USERNAME -p $AZURE_REGISTRY_PASSWORD
#    - docker push $AZURE_REGISTRY/services/user
#    - docker images

deploy:
  stage: deploy
  tags:
    - docker
  image:
    name: mcr.microsoft.com/azure-cli
    entrypoint: [""]
  script:
    - az login --service-principal -u "$AZURE_CLIENT_ID" -p "$AZURE_CLIENT_SECRET" --tenant "$AZURE_TENANT_ID"

# Install Docker
    - wget -O get-docker.sh https://get.docker.com
    - sh get-docker.sh

    # Start Docker daemon
    - sudo systemctl start docker

    # Verify Docker installation
    - docker --version

    - az acr login --name dentanoidRegistry
    #- az container create --resource-group Dentanoid --name user-service2 --image mydockerimage
    


  
